apiVersion: v1
kind: Config
clusters:
- name: k3s
  cluster:
    server: ${K3S_SERVER}
    insecure-skip-tls-verify: true
contexts:
- name: default
  context:
    cluster: k3s
    user: github-ci
current-context: default
users:
- name: github-ci
  user:
    token: ${K3S_TOKEN}